version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=Limupa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
